name: CI

on: 
  pull_request:
    branches:
      - main
      - develop

jobs:
  auth:
    name: Authentication service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        working-directory: auth
        run: yarn install --frozen-lockfile

      - name: Formatting, Linting and Testing
        working-directory: auth
        run: |
          yarn run prettier
          yarn run lint
          yarn run test
        